/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appointment: typeof import('./src/components/Appointment.vue')['default']
    AppointmentSchedule: typeof import('./src/components/booking.vue')['default']
    Booking: typeof import('./src/components/booking.vue')['default']
    BookingDone: typeof import('./src/components/bookingDone.vue')['default']
    HeaderLayout: typeof import('./src/components/HeaderLayout.vue')['default']
    Homepage: typeof import('./src/components/homepage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
